local Module = SUI:NewModule("Skins.Friendlist");

function Module:OnEnable()
    if (SUI:Color()) then
        for i, v in pairs({
            FriendsFrame.NineSlice.TopEdge,
            FriendsFrame.NineSlice.TopEdge,
            FriendsFrame.NineSlice.TopRightCorner,
            FriendsFrame.NineSlice.RightEdge,
            FriendsFrame.NineSlice.BottomRightCorner,
            FriendsFrame.NineSlice.BottomEdge,
            FriendsFrame.NineSlice.BottomLeftCorner,
            FriendsFrame.NineSlice.LeftEdge,
            FriendsFrame.NineSlice.TopLeftCorner,
            FriendsFriendsFrame.Border.TopEdge,
            FriendsFriendsFrame.Border.RightEdge,
            FriendsFriendsFrame.Border.BottomEdge,
            FriendsFriendsFrame.Border.LeftEdge,
            FriendsFriendsFrame.Border.TopRightCorner,
            FriendsFriendsFrame.Border.TopLeftCorner,
            FriendsFriendsFrame.Border.BottomLeftCorner,
            FriendsFriendsFrame.Border.BottomRightCorner,
            FriendsTabHeaderTab1.Left,
            FriendsTabHeaderTab1.Middle,
            FriendsTabHeaderTab1.Right,
            FriendsTabHeaderTab1.LeftActive,
            FriendsTabHeaderTab1.MiddleActive,
            FriendsTabHeaderTab1.RightActive,
            FriendsTabHeaderTab1.LeftHighlight,
            FriendsTabHeaderTab1.MiddleHighlight,
            FriendsTabHeaderTab1.RightHighlight,
            FriendsTabHeaderTab2.Left,
            FriendsTabHeaderTab2.Middle,
            FriendsTabHeaderTab2.Right,
            FriendsTabHeaderTab2.LeftActive,
            FriendsTabHeaderTab2.MiddleActive,
            FriendsTabHeaderTab2.RightActive,
            FriendsTabHeaderTab2.LeftHighlight,
            FriendsTabHeaderTab2.MiddleHighlight,
            FriendsTabHeaderTab2.RightHighlight,
            FriendsTabHeaderTab3.Left,
            FriendsTabHeaderTab3.Middle,
            FriendsTabHeaderTab3.Right,
            FriendsTabHeaderTab3.LeftActive,
            FriendsTabHeaderTab3.MiddleActive,
            FriendsTabHeaderTab3.RightActive,
            FriendsTabHeaderTab3.LeftHighlight,
            FriendsTabHeaderTab3.MiddleHighlight,
            FriendsTabHeaderTab3.RightHighlight,
            FriendsFrameTab1.Left,
            FriendsFrameTab1.Middle,
            FriendsFrameTab1.Right,
            FriendsFrameTab1.LeftActive,
            FriendsFrameTab1.MiddleActive,
            FriendsFrameTab1.RightActive,
            FriendsFrameTab1.LeftHighlight,
            FriendsFrameTab1.MiddleHighlight,
            FriendsFrameTab1.RightHighlight,
            FriendsFrameTab2.Left,
            FriendsFrameTab2.Middle,
            FriendsFrameTab2.Right,
            FriendsFrameTab2.LeftActive,
            FriendsFrameTab2.MiddleActive,
            FriendsFrameTab2.RightActive,
            FriendsFrameTab2.LeftHighlight,
            FriendsFrameTab2.MiddleHighlight,
            FriendsFrameTab2.RightHighlight,
            FriendsFrameTab3.Left,
            FriendsFrameTab3.Middle,
            FriendsFrameTab3.Right,
            FriendsFrameTab3.LeftActive,
            FriendsFrameTab3.MiddleActive,
            FriendsFrameTab3.RightActive,
            FriendsFrameTab3.LeftHighlight,
            FriendsFrameTab3.MiddleHighlight,
            FriendsFrameTab3.RightHighlight,
            FriendsFrameTab4.Left,
            FriendsFrameTab4.Middle,
            FriendsFrameTab4.Right,
            FriendsFrameTab4.LeftActive,
            FriendsFrameTab4.MiddleActive,
            FriendsFrameTab4.RightActive,
            FriendsFrameTab4.LeftHighlight,
            FriendsFrameTab4.MiddleHighlight,
            FriendsFrameTab4.RightHighlight,
            RecruitAFriendFrame.RecruitList.ScrollFrameInset.NineSlice.TopEdge,
            RecruitAFriendFrame.RecruitList.ScrollFrameInset.NineSlice.TopLeftCorner,
            RecruitAFriendFrame.RecruitList.ScrollFrameInset.NineSlice.TopRightCorner,
            RecruitAFriendFrame.RecruitList.ScrollFrameInset.NineSlice.LeftEdge,
            RecruitAFriendFrame.RecruitList.ScrollFrameInset.NineSlice.RightEdge,
            RecruitAFriendFrame.RecruitList.ScrollFrameInset.NineSlice.BottomEdge,
            RecruitAFriendFrame.RecruitList.ScrollFrameInset.NineSlice.BottomLeftCorner,
            RecruitAFriendFrame.RecruitList.ScrollFrameInset.NineSlice.BottomRightCorner,
        }) do
            v:SetVertexColor(unpack(SUI:Color(0.15)))
        end
        for i, v in pairs({
            FriendsFrame.Bg,
            FriendsFrame.TitleBg,
            FriendsFrameInset.NineSlice.TopEdge,
            FriendsFrameInset.NineSlice.TopEdge,
            FriendsFrameInset.NineSlice.TopRightCorner,
            FriendsFrameInset.NineSlice.RightEdge,
            FriendsFrameInset.NineSlice.BottomRightCorner,
            FriendsFrameInset.NineSlice.BottomEdge,
            FriendsFrameInset.NineSlice.BottomLeftCorner,
            FriendsFrameInset.NineSlice.LeftEdge,
            FriendsFrameInset.NineSlice.TopLeftCorner
        }) do
            v:SetVertexColor(unpack(SUI:Color(0.15)))
        end

        for i, v in pairs({WhoFrameListInset.NineSlice:GetRegions()}) do
            v:SetVertexColor(unpack(SUI:Color(0.15)))
        end

        for i, v in pairs({WhoFrameEditBoxInset.NineSlice:GetRegions()}) do
            v:SetVertexColor(unpack(SUI:Color(0.15)))
        end
    end
end
