local Module = SUI:NewModule("Skins.LFG");

function Module:OnEnable()
    if (SUI:Color()) then
        SUI:Skin(GroupFinderFrame)
        SUI:Skin(PVEFrame)
        SUI:Skin(LFDParentFrame)
        SUI:Skin(PVEFrameLeftInset)
        SUI:Skin(LFDParentFrameInset)
        SUI:Skin(LFDQueueFrame)
        SUI:Skin(LFDQueueFrameTypeDropDown)
        SUI:Skin(PVEFrame.shadows)
        SUI:Skin(LFGListPVEStub)
        SUI:Skin(LFGDungeonReadyDialog.Border)
        SUI:Skin(LFGDungeonReadyStatus.Border)
        SUI:Skin(LFGListFrame.CategorySelection.Inset)
        SUI:Skin(LFGListFrame.CategorySelection.StartGroupButton)
        SUI:Skin(LFGListFrame.CategorySelection.FindGroupButton)
        SUI:Skin(LFGListFrame.SearchPanel.ScrollBox.Shadows)
        SUI:Skin(LFGListFrame.SearchPanel.ScrollBox)
        SUI:Skin(LFGListFrame.SearchPanel.ResultsInset)
        SUI:Skin(LFGListFrame.SearchPanel.BackButton)
        SUI:Skin(LFGListFrame.SearchPanel.SignUpButton)
        SUI:Skin(LFGListFrame.SearchPanel.ScrollBox.StartGroupButton)
        SUI:Skin(LFDQueueFrameFindGroupButton)
        SUI:Skin(LFGListFrame.EntryCreation.CancelButton)
        SUI:Skin(LFGListFrame.EntryCreation.ListGroupButton)
        SUI:Skin(LFGListFrame.EntryCreation.Inset)
        SUI:Skin(LFGListApplicationDialog.SignUpButton)
        SUI:Skin(LFGListApplicationDialog.CancelButton)
        SUI:Skin(LFGListApplicationDialog.Border)
        SUI:Skin(LFDRoleCheckPopup.Border)
        SUI:Skin(LFDRoleCheckPopupAcceptButton)
        SUI:Skin(LFDRoleCheckPopupDeclineButton)
        SUI:Skin(LFGListFrame.ApplicationViewer)
        SUI:Skin(LFGListFrame.ApplicationViewer.Inset)
        SUI:Skin(LFGListFrame.ApplicationViewer.BrowseGroupsButton)
        SUI:Skin(LFGListFrame.ApplicationViewer.RemoveEntryButton)
        SUI:Skin(LFGListFrame.ApplicationViewer.EditButton)
        SUI:Skin(LFGListFrame.SearchPanel.BackToGroupButton)
        SUI:Skin(LFGListFrame.ApplicationViewer.NameColumnHeader)
        SUI:Skin(LFGListFrame.ApplicationViewer.RoleColumnHeader)
        SUI:Skin(LFGListFrame.ApplicationViewer.ItemLevelColumnHeader)
        SUI:Skin(LFGListEntryCreationGroupDropDown)
        SUI:Skin(LFGListEntryCreationActivityDropDown)
        SUI:Skin(LFGListFrame.EntryCreation.Name)
        SUI:Skin(LFGListCreationDescription)
        SUI:Skin(LFGListFrame.EntryCreation.ItemLevel.EditBox)
        SUI:Skin(LFGListFrame.EntryCreation.VoiceChat.EditBox)
        SUI:Skin(LFGListCreateRoleDialog.Border)
        SUI:Skin(LFGListCreateRoleDialog.SignUpButton)
        SUI:Skin(LFGListCreateRoleDialog.CancelButton)
        SUI:Skin(LFGListInviteDialog.Border)
        SUI:Skin(LFGListFrame.SearchPanel.FilterButton)
        SUI:Skin(LFGListFrame.SearchPanel.SearchBox)
        SUI:Skin(RolePollPopup.Border)
        SUI:Skin(RolePollPopupAcceptButton)
        LFGListFrame.ApplicationViewer.ScrollBox.NoApplicants:SetTextColor(.8, .8, .8)

        -- Buttons
        SUI:Skin({
            LFGListFrame.CategorySelection.StartGroupButton.Left,
            LFGListFrame.CategorySelection.StartGroupButton.Middle,
            LFGListFrame.CategorySelection.StartGroupButton.Right,
            LFGListFrame.CategorySelection.FindGroupButton.Left,
            LFGListFrame.CategorySelection.FindGroupButton.Middle,
            LFGListFrame.CategorySelection.FindGroupButton.Right,
            LFGListFrame.SearchPanel.BackButton.Left,
            LFGListFrame.SearchPanel.BackButton.Middle,
            LFGListFrame.SearchPanel.BackButton.Right,
            LFGListFrame.SearchPanel.SignUpButton.Left,
            LFGListFrame.SearchPanel.SignUpButton.Middle,
            LFGListFrame.SearchPanel.SignUpButton.Right,
            LFGListFrame.SearchPanel.ScrollBox.StartGroupButton.Left,
            LFGListFrame.SearchPanel.ScrollBox.StartGroupButton.Middle,
            LFGListFrame.SearchPanel.ScrollBox.StartGroupButton.Right,
            LFDQueueFrameFindGroupButton.Left,
            LFDQueueFrameFindGroupButton.Middle,
            LFDQueueFrameFindGroupButton.Right,
            LFGListFrame.EntryCreation.CancelButton.Left,
            LFGListFrame.EntryCreation.CancelButton.Middle,
            LFGListFrame.EntryCreation.CancelButton.Right,
            LFGListFrame.EntryCreation.ListGroupButton.Left,
            LFGListFrame.EntryCreation.ListGroupButton.Middle,
            LFGListFrame.EntryCreation.ListGroupButton.Right,
            LFGListApplicationDialog.SignUpButton.Left,
            LFGListApplicationDialog.SignUpButton.Middle,
            LFGListApplicationDialog.SignUpButton.Right,
            LFGListApplicationDialog.CancelButton.Left,
            LFGListApplicationDialog.CancelButton.Middle,
            LFGListApplicationDialog.CancelButton.Right,
            LFDRoleCheckPopupAcceptButton.Left,
            LFDRoleCheckPopupAcceptButton.Middle,
            LFDRoleCheckPopupAcceptButton.Right,
            LFDRoleCheckPopupDeclineButton.Left,
            LFDRoleCheckPopupDeclineButton.Middle,
            LFDRoleCheckPopupDeclineButton.Right,
            LFGListFrame.ApplicationViewer.BrowseGroupsButton.Left,
            LFGListFrame.ApplicationViewer.BrowseGroupsButton.Middle,
            LFGListFrame.ApplicationViewer.BrowseGroupsButton.Right,
            LFGListFrame.ApplicationViewer.RemoveEntryButton.Left,
            LFGListFrame.ApplicationViewer.RemoveEntryButton.Middle,
            LFGListFrame.ApplicationViewer.RemoveEntryButton.Right,
            LFGListFrame.ApplicationViewer.EditButton.Left,
            LFGListFrame.ApplicationViewer.EditButton.Middle,
            LFGListFrame.ApplicationViewer.EditButton.Right,
            LFGListFrame.SearchPanel.BackToGroupButton.Left,
            LFGListFrame.SearchPanel.BackToGroupButton.Middle,
            LFGListFrame.SearchPanel.BackToGroupButton.Right,
            LFGListCreateRoleDialog.SignUpButton.Left,
            LFGListCreateRoleDialog.SignUpButton.Middle,
            LFGListCreateRoleDialog.SignUpButton.Right,
            LFGListCreateRoleDialog.CancelButton.Left,
            LFGListCreateRoleDialog.CancelButton.Middle,
            LFGListCreateRoleDialog.CancelButton.Right,
            LFGDungeonReadyDialogEnterDungeonButton.Left,
            LFGDungeonReadyDialogEnterDungeonButton.Middle,
            LFGDungeonReadyDialogEnterDungeonButton.Right,
            LFGDungeonReadyDialogLeaveQueueButton.Left,
            LFGDungeonReadyDialogLeaveQueueButton.Middle,
            LFGDungeonReadyDialogLeaveQueueButton.Right,
            LFGListInviteDialog.AcceptButton.Left,
            LFGListInviteDialog.AcceptButton.Middle,
            LFGListInviteDialog.AcceptButton.Right,
            LFGListInviteDialog.DeclineButton.Left,
            LFGListInviteDialog.DeclineButton.Middle,
            LFGListInviteDialog.DeclineButton.Right,
            LFGListInviteDialog.AcknowledgeButton.Left,
            LFGListInviteDialog.AcknowledgeButton.Middle,
            LFGListInviteDialog.AcknowledgeButton.Right
        }, false, true, false, true)
    end
end
